### PR TITLE
Add preserveContext option

### PR DESCRIPTION
**Pull request by NSLS**
I have tested it on my project, everything seems to work.
However, `npm run test` shows that some unit-tests fail, but it seems like they are failing in the current master as well, so I haven't tried to fix it

### CODE REVIEW

**Comment by NSLS** [comment]
Also closes #37

**Comment by juliancwirko** [comment]
Yes, tests are broken ;) This is not your fault. We need to prepare better testing environment for this lib. There is an 'issue' for that too.
Thanks for the PR. I'll test it manually. 
If this is something which we can enable/disable, and it will not break anything else I think we could merge that, because there was some questions regarding contexts, so it seems that this is needed.

**Comment by NSLS** [comment]
Yes, the new option is disabled by default, so nothing should change for the users after the update unless they turn it on manually. But better merge it only after testing, maybe there is something I've missed.

**Comment by samvk** [comment]
Solved my issue with not being able to use translations in alerts. Thank you. Hope this is merged into master.

**Comment by NSLS** [comment]
@juliancwirko So can this be merged already? It's been quite a long time

**Comment by juliancwirko** [comment]
Thanks. Sorry for the delay.

**Pull request merged**
