### PR TITLE
alert also accepts a react component

### PR DESCRIPTION
**Pull request by FredericHeem**

### CODE REVIEW

**Comment by juliancwirko** [comment]
Hi, this is a very nice idea, but I wonder if it will work in all cases. Have you tested it with components which has more complicated structures? I'll try to find some time to test it.

**Comment by FredericHeem** [comment]
FYI, here is the component being rendered: https://github.com/FredericHeem/starhackit/blob/master/client/src/app/parts/core/components/notification.js
It is working fine on my side.

**Comment by FredericHeem** [comment]
Any news on merging this PR ? I'm fed up to see the react warnings polluting the console log

**Comment by juliancwirko** [comment]
Hi, sorry about that, I plan to get back to this library. I hadn't enough time (open source life time ;)). But give me some time and everything will be on the proper way :)

**Pull request merged**
